Vagrant.configure("2") do |config|

  config.vm.define "proj"

  config.vm.network "private_network", ip: "192.168.56.8"

  config.vm.box = "ubuntu/focal64"

  config.vm.disk :disk, size: "40GB", primary: true

  config.vm.provider "virtualbox" do |v|
    v.memory = 8192
    v.cpus = 4
  end

end