version: "3.7"

services:
  mysql:
    image: mysql
    container_name: mysql-authy
    volumes:
      - mysql-data:/var/lib/mysql
    environment: 
      MYSQL_ROOT_PASSWORD: 12345
      MYSQL_DATABASE: authy
    ports:
    - 3306:3306

volumes:
  mysql-data: