apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-web
  namespace: default
spec:
  rules: 
  - host: web.com
    http:
      paths:
        - path: /web
          pathType: Prefix
          backend:
            # serviceName: kubernetes-dashboard
            # servicePort: 80
            service:
              name: my-service
              port: 
                number: 80