
Vagrant.configure("2") do |config|

  config.vm.define "fss"

  # config.ssh.host = '192.168.56.5'
  # config.ssh.port = '2222'


  # config.vm.network "forwarded_port", guest:6666, host:6666
  config.vm.network "private_network", ip: "192.168.56.5"

  config.vm.box = "ubuntu/focal64"
  # config.vm.box = "bento/centos-7.6"

  config.vm.provider "virtualbox" do |v|
    v.memory = 4096
    v.cpus = 3
  end


end
