version: "3.7"
services:
  minio:
    image: minio/minio
    container_name: minio
    command: server /data --console-address ":9001"
    environment:
      - MINIO_ROOT_USER=root
      - MINIO_ROOT_PASSWORD=12345678
    restart: always
    ports:
      - "9000:9000"
      - "9001:9001"
