Vagrant.configure("2") do |config|

  config.vm.define "db"

  config.vm.network "private_network", ip: "192.168.56.7"

  config.vm.box = "ubuntu/focal64"

  config.vm.disk :disk, size: "20GB", primary: true

  config.vm.provider "virtualbox" do |v|
    v.memory = 4096
    v.cpus = 3
  end


end
